_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.9.6
            "5": 0.19.10
            "8":
                - 1
                - 5
            "12": 0.19.10
            "13": darwin-arm64
beam_width:
    value: 5
bidirectional:
    value: true
dec_layers:
    value: 3
dropout:
    value: 0.3
emb_size:
    value: 64
enc_layers:
    value: 2
epochs:
    value: 20
hidden_size:
    value: 256
layer_type:
    value: lstm
learning_rate:
    value: 0.001
teacher_force_ratio:
    value: 0.5
val_beam_search:
    value: false
