wandb_version: 1

beam_width:
  value: 1
bidirectional:
  value: false
dec_layers:
  value: 2
dropout:
  value: 0.3
emb_size:
  value: 16
enc_layers:
  value: 3
epochs:
  value: 20
hidden_size:
  value: 64
layer_type:
  value: lstm
learning_rate:
  value: 0.001
teacher_force_ratio:
  value: 1
val_beam_search:
  value: false
