wandb_version: 1

beam_width:
  value: 1
bidirectional:
  value: true
dec_layers:
  value: 1
dropout:
  value: 0.2
emb_size:
  value: 64
enc_layers:
  value: 2
epochs:
  value: 3
hidden_size:
  value: 64
layer_type:
  value: gru
learning_rate:
  value: 0.001
teacher_force_ratio:
  value: 0.3
val_beam_search:
  value: true
