wandb_version: 1

beam_width:
  value: 3
bidirectional:
  value: true
dec_layers:
  value: 1
dropout:
  value: 0.3
emb_size:
  value: 16
enc_layers:
  value: 3
epochs:
  value: 30
hidden_size:
  value: 256
layer_type:
  value: gru
learning_rate:
  value: 0.001
teacher_force_ratio:
  value: 0.5
val_beam_search:
  value: true
