wandb_version: 1

beam_width:
  value: 5
bidirectional:
  value: true
dec_layers:
  value: 3
dropout:
  value: 0.3
emb_size:
  value: 64
enc_layers:
  value: 2
epochs:
  value: 20
hidden_size:
  value: 256
layer_type:
  value: lstm
learning_rate:
  value: 0.001
teacher_force_ratio:
  value: 0.5
val_beam_search:
  value: false
