wandb_version: 1

beam_width:
  value: 1
bidirectional:
  value: false
dec_layers:
  value: 1
dropout:
  value: 0.2
emb_size:
  value: 32
enc_layers:
  value: 1
epochs:
  value: 2
hidden_size:
  value: 256
layer_type:
  value: lstm
learning_rate:
  value: 0.0005
teacher_force_ratio:
  value: 1
val_beam_search:
  value: false
