wandb_version: 1

beam_width:
  value: 5
bidirectional:
  value: true
dec_layers:
  value: 1
dropout:
  value: 0.2
emb_size:
  value: 16
enc_layers:
  value: 2
epochs:
  value: 3
hidden_size:
  value: 64
layer_type:
  value: rnn
learning_rate:
  value: 0.0001
teacher_force_ratio:
  value: 1
val_beam_search:
  value: true
