wandb_version: 1

beam_width:
  value: 1
bidirectional:
  value: true
dec_layers:
  value: 3
dropout:
  value: 0.3
emb_size:
  value: 32
enc_layers:
  value: 1
epochs:
  value: 30
hidden_size:
  value: 32
layer_type:
  value: lstm
learning_rate:
  value: 0.0001
teacher_force_ratio:
  value: 0.7
val_beam_search:
  value: true
