wandb_version: 1

beam_width:
  value: 1
bidirectional:
  value: false
dec_layers:
  value: 3
dropout:
  value: 0.2
emb_size:
  value: 16
enc_layers:
  value: 3
epochs:
  value: 30
hidden_size:
  value: 32
layer_type:
  value: gru
learning_rate:
  value: 0.001
teacher_force_ratio:
  value: 0.7
val_beam_search:
  value: false
