wandb_version: 1

beam_width:
  value: 3
bidirectional:
  value: false
dec_layers:
  value: 1
dropout:
  value: 0.3
emb_size:
  value: 32
enc_layers:
  value: 1
epochs:
  value: 30
hidden_size:
  value: 32
layer_type:
  value: lstm
learning_rate:
  value: 0.0005
teacher_force_ratio:
  value: 0.5
val_beam_search:
  value: true
