wandb_version: 1

beam_width:
  value: 3
bidirectional:
  value: false
dec_layers:
  value: 1
dropout:
  value: 0.3
emb_size:
  value: 16
enc_layers:
  value: 1
epochs:
  value: 3
hidden_size:
  value: 64
layer_type:
  value: gru
learning_rate:
  value: 0.001
teacher_force_ratio:
  value: 1
val_beam_search:
  value: true
